############################################################################
# PROGRAM:  NHFSPUF.R                                                      #
#                                                                          #
# SOFTWARE:  R Version 2.8.1                                              #
#                                                                          #
# PURPOSE:  THIS R   PROGRAM CREATES A PERMANENT R DATASET                 #
#                FROM THE  NHFS PUBLIC-USE ASCII FILE                      #
#                                                                          #
# NOTES:    THIS PROGRAM IS DIVIDED INTO SEVEN STEPS AS FOLLOWS:           #
#                                                                          #
# STEP 1:   LOAD AN R PACKAGE AND ASSIGN FILE NAMES                        #
#                                                                          #
#		 ONE R PACKAGE FOR TWO FUNCTIONS (CONTENTS, WTD.TABLE)             #
#		 WILL BE LOADED	                                                   #
#		 THE USER CAN ENTER THE PATH TO THE ASCII DATA FILE AND            #
#		 THE PATH WHERE THE R DATASET WILL BE CREATED                      #
#                                                                          #
# STEP 2:   CREATE FORMATS                                                 #
#                                                                          #
# STEP 3:   READ THE FLAT DATA FILE                                        #
#                                                                          #
# STEP 4:   ASSIGN VARIABLE LABELS                                         #
#                                                                          #
# STEP 5:   CREATE A PERMANENT R DATASET                                   #
#                                                                          #
# STEP 6:   ASSIGN FORMATS                                                 #
#                                                                          #
#	   FORMATS ARE APPLICABLE ONLY TO CATEGORICAL VARIABLES IN R	       #
#                                                                          #
# STEP 7:   CONTENTS AND STATISTICAL ESTIMATES(FREQUENCY) EXAMPLE          #
#                                                                          #
############################################################################

############################################################################
# Step 1:   LOAD R PACKAGES AND ASSIGN FILE NAMES                          #
############################################################################
#Users may need to install the Hmisc library before invoking it.
library(Hmisc) #TO USE contents()

#---USE SLASH(/) TO SEPERATE A FILE PATH---#
PUF <- "path-to-data"

flatfile <- "path-to-file/NHFSPUF.DAT"



############################################################################
# Step 2:   CREATE FORMATS                                                 #
############################################################################

NOFMTClevels=c( )
NOFMTClabels=c("Missing")

FLAGlevels=c(0,1)
FLAGlabels=c("No", "Yes")

EDUCATIONlevels=c(1,2,3,4)
EDUCATIONlabels=c("< 12 Years", "12 Years", "Some College", "College Graduate")

POVSTATlevels=c(1,2,3,4)
POVSTATlabels=c("> $75,000", "<= $75,000, Above Poverty", "Below Poverty", "Unknown")

GENDERlevels=c(1,2)
GENDERlabels=c("Male", "Female")

HHSREGIONlevels=c(1,10,2,3,4,5,6,7,8,9)
HHSREGIONlabels=c("Region I:  CT,ME,MA,NH,RI,VT", "Region X:  AK,ID,OR,WA", "Region II:  NJ,NY", "Region III:  DE,DC,MD,PA,VA,WV", "Region IV:  AL,FL,GA,KY,MS,NC,SC,TN", "Region V:  IL,IN,MI,MN,OH,WI", "Region VI:  AR,LA,NM,OK,TX",
"Region VII:  IA,KS,MO,NE", "Region VIII:  CO,MT,ND,SD,UT,WY", "Region IX:  AZ,CA,HI,NV")

MSAlevels=c(1,2,3)
MSAlabels=c("MSA, Principle City", "MSA, Not Principle  City", "Non-MSA")

CENREGlevels=c(1,2,3,4)
CENREGlabels=c("Region 1:  CT,ME,MA,NH,VT,RI,NJ,NY,PA", "Region 2:  IL,IN,MI,OH,WI,IA,KS,MN,MO,NE,ND,SD", "Region 3:  DE,DC,FL,GA,MD,NC,SC,VA,WV,AL,KY,MS,TN,AR,LA,OK,TX", "Region 4:  AZ,CO,ID,MT,NV,NM,UT,WY,AK,CA,HI,OR,WA")

HSPlevels=c(1,2,77,99)
HSPlabels=c("Yes", "No", "Don't Know", "Refused")

RACETH4_levels=c(1,2,3,4)
RACETH4_labels=c("Hispanic", "Non-Hispanic, Black Only", "Non-Hispanic, White Only", "Non-Hispanic, Other or Multiple Races")

SFLAGlevels=c("","01","02","77","99")
SFLAGlabels=c("Missing", "Yes", "No", "Don't Know", "Refused")

SHOTMONTHlevels=c(1,10,11,12,2,3,4,5,6,7,77,8,9,99)
SHOTMONTHlabels=c("January", "October", "November", "December", "February", "March", "April", "May", "June", "July", "Don't Know", "August", "September", "Refused")

SHOTYEARlevels=c(777,999)
SHOTYEARlabels=c("Don't Know", "Refused")

SNOFMTlevels=c(77,99)
SNOFMTlabels=c("Don't Know", "Refused")

OPIN1_levels=c("","01","02","03","04","77","99")
OPIN1_labels=c("Missing", "Very Effective", "Somewhat Effective", "Not Very Effective", "Not At All Effective", "Don't Know", "Refused")

OPIN2_levels=c("","01","02","03","04","77","99")
OPIN2_labels=c("Missing", "Very High", "Somewhat High", "Somewhat Low", "Very Low", "Don't Know", "Refused")

OPIN3_levels=c("","01","02","03","04","77","99")
OPIN3_labels=c("Missing", "Very Worried", "Somewhat Worried", "Not Very Worried", "Not At All Worried", "Don't Know", "Refused")

LNGlevels=c(1,2,3)
LNGlabels=c("English", "Spanish", "Other Language")

TYPElevels=c("1","2")
TYPElabels=c("Injection/Shot", "Nasal Spray/Mist")

INCCAT1_levels=c(1,2,3,4,5,6,7,77,8,99)
INCCAT1_labels=c("<= $10,000", "$10,001 - $15,000", "$15,001 - $25,000", "$25,001 - $35,000", "$35,001 - $50,000", "$50,001 - $75,000", "$75,001 - $100,000", "Don't Know", "> $100,000", "Refused")

SAMPDESIG2_levels=c("","FC","FR")
SAMPDESIG2_labels=c("Missing", "Cell Phone", "Landline")

SUBGRP2_levels=c("","A","C")
SUBGRP2_labels=c("Missing", "Adult 18+ Years", "Child 6 Months - 17 Years")

AGEGRP3_levels=c(1,2,3,4,5,6,7)
AGEGRP3_labels=c("6 Months - 9 Years", "10 - 17 Years", "18 - 34 Years", "35 - 44 Years", "45 - 54 Years", "55 - 64 Years", "65+ Years")

MARSTAT2_levels=c(1,2)
MARSTAT2_labels=c("Married", "Not Married")

RCE2_levels=c(1,2,3)
RCE2_labels=c("WHITE ONLY", "BLACK ONLY", "MULTIPLE OR OTHER RACES")

RENTOWN2_levels=c("","01","02","77","99")
RENTOWN2_labels=c("Missing", "Home is Owned", "Home is Rented or Other Arrangement", "Don't Know", "Refused")

WORKTYPE2_levels=c("","01","02","03","77","99")
WORKTYPE2_labels=c("Missing", "Employed", "Unemployed", "Not in Labor Force", "Don't Know", "Refused")

INDSTRlevels=c(1,10,11,12,13,14,15,16,17,18,19,2,20,21,3,4,5,6,7,8,9,97,98,99)
INDSTRlabels=c("Agriculture, Forestry, Fishing, and Hunting Industries", "Finance and Insurance Industries", "Real Estate and Rental and Leasing Industries", "Professional, Scientific, and Technical Services Industries",
"Management of Companies and Enterprises Industries", "Administrative and Support and Waste Management and Remediation Services Industries", "Education Services Industries", "Health Care and Social Assistance Industries",
"Arts, Entertainment, and Recreation Industries Administration) Industries", "Accommodation and Food Services Industries", "Other Services (except Public)", "Mining Industries", "Public Administration Industries", "Armed Forces", "Utilities Industries",
"Construction Industries", "Manufacturing Industries", "Wholesale Trade Industries", "Retail Trade Industries", "Transportation and Warehousing Industries", "Information Industries", "Refused, classified", "Not ascertained", "Do not know")

OCCPNlevels=c(1,10,11,12,13,14,15,16,17,18,19,2,20,21,22,23,3,4,5,6,7,8,9,97,98,99)
OCCPNlabels=c("Management Occupations", "Healthcare Practitioners and Technical Occupations", "Healthcare Support Occupations", "Protective Service Occupations", "Food Preparation and Serving Related Occupations",
"Building and Grounds Cleaning and Maintenance Occupations", "Personal Care and Service Occupations", "Sales and Related Occupations", "Office and Administrative Support Occupations", "Farming, Fishing, and Forestry Occupations",
"Construction and Extraction Occupations", "Business and Financial Operations Occupations", "Installation, Maintenance, and Repair Occupations", "Production Occupations", "Transportation and Material Moving Occupations", "Military Specific Occupations",
"Computer and Mathematical Occupations", "Architecture and Engineering Occupations", "Life, Physical, and Social Science Occupations", "Community and Social Services Occupations", "Legal Occupations", "Education, Training, and Library Occupations';",
"Arts, Design, Entertainment, Sports and Media Occupations", "Refused, classified", "Not ascertained", "Do not know")

STATENUMlevels=c(1,10,11,12,13,14,15,16,17,18,19,2,20,21,22,23,24,25,26,27,28,29,3,30,31,32,33,34,35,36,37,38,39,4,40,41,42,43,44,45,46,47,48,49,5,50,51,52,53,54,55,56,6,7,78,8,9)
STATENUMlabels=c("ALABAMA", "DELAWARE", "DISTRICT OF COLUMBIA", "FLORIDA", "GEORGIA", "", "HAWAII", "IDAHO", "ILLINOIS", "INDIANA", "IOWA", "ALASKA", "KANSAS", "KENTUCKY", "LOUISIANA", "MAINE", "MARYLAND", "MASSACHUSETTS", "MICHIGAN", "MINNESOTA",
"MISSISSIPPI", "MISSOURI", "", "MONTANA", "NEBRASKA", "NEVADA", "NEW HAMPSHIRE", "NEW JERSEY", "NEW MEXICO", "NEW YORK", "NORTH CAROLINA", "NORTH DAKOTA", "OHIO", "ARIZONA", "OKLAHOMA", "OREGON", "PENNSYLVANIA", "", "RHODE ISLAND", "SOUTH CAROLINA",
"SOUTH DAKOTA", "TENNESSEE", "TEXAS", "UTAH", "ARKANSAS", "VERMONT", "VIRGINIA", "", "WASHINGTON", "WEST VIRGINIA", "WISCONSIN", "WYOMING", "CALIFORNIA", "", "U.S.  VIRGIN ISLANDS", "COLORADO", "CONNECTICUT")


############################################################################
# Step 3:   READ THE FLAT DATA FILE                                        #
############################################################################

LIST.NAMEWIDTH <-
c("INT_MONTH",5,
"LANGUAGE",1,
"SAMP_DESIG",2,
"SEQNUMHH",5,
"SEQNUMP",6,
"SUBGROUP",1,
"VACC1_H1N1_M",2,
"VACC1_H1N1_T",1,
"VACC1_H1N1_Y",4,
"VACC1_SEAS_M",2,
"VACC1_SEAS_T",1,
"VACC1_SEAS_Y",4,
"VACC2_H1N1_M",2,
"VACC2_H1N1_T",1,
"VACC2_H1N1_Y",4,
"VACC2_SEAS_M",2,
"VACC2_SEAS_T",1,
"VACC2_SEAS_Y",4,
"VACC_H1N1_COUNT",1,
"VACC_H1N1_F",1,
"VACC_PNEU_COUNT",1,
"VACC_PNEU_F",1,
"VACC_SEAS_COUNT",1,
"VACC_SEAS_F",1,
"B_H1N1_ANTIV",1,
"B_H1N1_AVOID",1,
"B_H1N1_FMASK",1,
"B_H1N1_HANDS",1,
"B_H1N1_LARGE",1,
"B_H1N1_RCONT",1,
"B_H1N1_TOUCH",1,
"CONCERN_DKNW_F",1,
"CONCERN_NONE_F",1,
"CONCERN_NOTV_F",1,
"CONCERN_REFD_F",1,
"CONCERN_SOME_F",1,
"CONCERN_VERY_F",1,
"HQ23",2,
"HQ24",2,
"HQ24_B",2,
"INT_H1N1_DKNW_F",1,
"INT_H1N1_DNOT_F",1,
"INT_H1N1_DYES_F",1,
"INT_H1N1_PNOT_F",1,
"INT_H1N1_PYES_F",1,
"INT_H1N1_REFD_F",1,
"INT_NEXT_DKNW_F",1,
"INT_NEXT_DNOT_F",1,
"INT_NEXT_DYES_F",1,
"INT_NEXT_PNOT_F",1,
"INT_NEXT_PYES_F",1,
"INT_NEXT_REFD_F",1,
"INT_SEAS_DKNW_F",1,
"INT_SEAS_DNOT_F",1,
"INT_SEAS_DYES_F",1,
"INT_SEAS_PNOT_F",1,
"INT_SEAS_PYES_F",1,
"INT_SEAS_REFD_F",1,
"KNOW_H1N1_ALOT_F",1,
"KNOW_H1N1_DKNW_F",1,
"KNOW_H1N1_LITL_F",1,
"KNOW_H1N1_NONE_F",1,
"KNOW_H1N1_REFD_F",1,
"PLACE_H1N1_CLIN_F",1,
"PLACE_H1N1_DEPT_F",1,
"PLACE_H1N1_DKNW_F",1,
"PLACE_H1N1_DOCT_F",1,
"PLACE_H1N1_HOSP_F",1,
"PLACE_H1N1_MTRY_F",1,
"PLACE_H1N1_OTHM_F",1,
"PLACE_H1N1_OTHN_F",1,
"PLACE_H1N1_PHRM_F",1,
"PLACE_H1N1_REFD_F",1,
"PLACE_H1N1_SCHL_F",1,
"PLACE_H1N1_SCTR_F",1,
"PLACE_H1N1_SMKT_F",1,
"PLACE_H1N1_WORK_F",1,
"PLACE_SEAS_CLIN_F",1,
"PLACE_SEAS_DEPT_F",1,
"PLACE_SEAS_DKNW_F",1,
"PLACE_SEAS_DOCT_F",1,
"PLACE_SEAS_HOSP_F",1,
"PLACE_SEAS_MTRY_F",1,
"PLACE_SEAS_OTHM_F",1,
"PLACE_SEAS_OTHN_F",1,
"PLACE_SEAS_PHRM_F",1,
"PLACE_SEAS_REFD_F",1,
"PLACE_SEAS_SCHL_F",1,
"PLACE_SEAS_SCTR_F",1,
"PLACE_SEAS_SMKT_F",1,
"PLACE_SEAS_WORK_F",1,
"Q23",2,
"Q24",2,
"Q24_B",2,
"REAS_NOH1N1_AHAD_F",1,
"REAS_NOH1N1_ALLG_F",1,
"REAS_NOH1N1_CANT_F",1,
"REAS_NOH1N1_COST_F",1,
"REAS_NOH1N1_DKNW_F",1,
"REAS_NOH1N1_DWRK_F",1,
"REAS_NOH1N1_GOTO_F",1,
"REAS_NOH1N1_NDOC_F",1,
"REAS_NOH1N1_NEVR_F",1,
"REAS_NOH1N1_NNDD_F",1,
"REAS_NOH1N1_NOTA_F",1,
"REAS_NOH1N1_OTHR_F",1,
"REAS_NOH1N1_REFD_F",1,
"REAS_NOH1N1_SAVE_F",1,
"REAS_NOH1N1_SEFF_F",1,
"REAS_NOH1N1_TIME_F",1,
"REAS_NOSEAS_AHAD_F",1,
"REAS_NOSEAS_ALLG_F",1,
"REAS_NOSEAS_CANT_F",1,
"REAS_NOSEAS_COST_F",1,
"REAS_NOSEAS_DKNW_F",1,
"REAS_NOSEAS_DWRK_F",1,
"REAS_NOSEAS_GOTO_F",1,
"REAS_NOSEAS_NDOC_F",1,
"REAS_NOSEAS_NEVR_F",1,
"REAS_NOSEAS_NNDD_F",1,
"REAS_NOSEAS_NOTA_F",1,
"REAS_NOSEAS_OTHR_F",1,
"REAS_NOSEAS_REFD_F",1,
"REAS_NOSEAS_SAVE_F",1,
"REAS_NOSEAS_SEFF_F",1,
"REAS_NOSEAS_TIME_F",1,
"DOCREC_BOTH_F",1,
"DOCREC_DKNW_F",1,
"DOCREC_H1N1_F",1,
"DOCREC_NTHR_F",1,
"DOCREC_REFD_F",1,
"DOCREC_SEAS_F",1,
"ILI_DIAG_H1N1_F",1,
"ILI_DIAG_SEAS_F",1,
"ILI_F",1,
"ILI_OTHER_F",1,
"ILI_TIME_OFF",2,
"ILI_TREAT_F",1,
"PSL_1",2,
"PSL_2",2,
"Q9",2,
"Q9_NUM",2,
"CHRONIC_MED_F",1,
"CLOSE_UNDER6MO_F",1,
"HEALTH_WORKER_F",1,
"PATIENT_CONTACT_F",1,
"AGEGRP",1,
"C_INSURE2",2,
"EDUCATION_COMP",1,
"HH_CHILD_R",1,
"HISP_I",1,
"INC_CAT1",1,
"INC_POV",1,
"INC_REF",4,
"INSURE",2,
"MARITAL",1,
"N_ADULT_R",1,
"N_PEOPLE_R",1,
"Q95",2,
"Q95_INDSTR",2,
"Q95_OCCPN",2,
"RACEETH4_I",1,
"RACE_I_R",1,
"RENT_OWN_R",2,
"SEX_I",1,
"CEN_REG",1,
"FLUWT",21,
"HHS_REGION",2,
"MSA3_I",1,
"MSA_DEF",8,
"STATE",2
)

NAMEWIDTH <- matrix(LIST.NAMEWIDTH, 171, 2, byrow=T, dimnames = list(NULL, c("VARIABLE","WIDTH")))
NA_STRING <- c(" ", ".", " .", "  .", "   .", "   .    ", " .              ", "    .              ", "     .              ", "     .             ")

NHFSPUF <- read.fwf(flatfile, widths= as.numeric(NAMEWIDTH[,2]), col.names = NAMEWIDTH[,1], na.strings= NA_STRING, as.is=TRUE)

NHFSPUF$SEQNUMHH <- as.character(NHFSPUF$SEQNUMHH)
NHFSPUF$SEQNUMP <- as.character(NHFSPUF$SEQNUMP)
NHFSPUF$INT_MONTH <- as.character(NHFSPUF$INT_MONTH)
NHFSPUF$SAMP_DESIG <- as.character(NHFSPUF$SAMP_DESIG)
NHFSPUF$SUBGROUP <- as.character(NHFSPUF$SUBGROUP)
NHFSPUF$HQ23 <- as.character(NHFSPUF$HQ23)
NHFSPUF$HQ24 <- as.character(NHFSPUF$HQ24)
NHFSPUF$HQ24_B <- as.character(NHFSPUF$HQ24_B)
NHFSPUF$Q23 <- as.character(NHFSPUF$Q23)
NHFSPUF$Q24 <- as.character(NHFSPUF$Q24)
NHFSPUF$Q24_B <- as.character(NHFSPUF$Q24_B)
NHFSPUF$PSL_1 <- as.character(NHFSPUF$PSL_1)
NHFSPUF$PSL_2 <- as.character(NHFSPUF$PSL_2)
NHFSPUF$Q9 <- as.character(NHFSPUF$Q9)
NHFSPUF$C_INSURE2 <- as.character(NHFSPUF$C_INSURE2)
NHFSPUF$INSURE <- as.character(NHFSPUF$INSURE)
NHFSPUF$Q95 <- as.character(NHFSPUF$Q95)
NHFSPUF$RENT_OWN_R <- as.character(NHFSPUF$RENT_OWN_R)
NHFSPUF$MSA_DEF <- as.character(NHFSPUF$MSA_DEF)

############################################################################
# Step 4:   ASSIGN VARIABLE LABELS                                         #
############################################################################

label(NHFSPUF$SEQNUMHH) <- "HOUSEHOLD IDENTIFIER"
label(NHFSPUF$SEQNUMP) <- "PERSON IDENTIFIER"
label(NHFSPUF$INT_MONTH) <- "MONTH OF INTERVIEW COMPLETION"
label(NHFSPUF$LANGUAGE) <- "LANGUAGE IN WHICH IN THE INTERVIEW WAS COMPLETED"
label(NHFSPUF$SAMP_DESIG) <- "SAMPLE DESIGNATION (LANDLINE VS CELL)"

label(NHFSPUF$SUBGROUP) <- "SUBGROUP DESIGNATION (ADULT OR CHILD)"
label(NHFSPUF$VACC_H1N1_COUNT) <- "NUMBER OF H1N1 FLU VACCINATIONS"
label(NHFSPUF$VACC_H1N1_F) <- "H1N1 FLU VACCINATION INDICATOR"
label(NHFSPUF$VACC_PNEU_COUNT) <- "NUMBER OF PPV23 VACCINE DOSES RECEIVED AS AN ADULT"
label(NHFSPUF$VACC_PNEU_F) <- "RECEIVED PPV23 VACCINE AS AN ADULT"

label(NHFSPUF$VACC_SEAS_COUNT) <- "NUMBER OF SEASONAL FLU VACCINATIONS"
label(NHFSPUF$VACC_SEAS_F) <- "SEASONAL FLU VACCINATION INDICATOR"
label(NHFSPUF$VACC1_H1N1_M) <- "MONTH OF FIRST H1N1 VACCINATION"
label(NHFSPUF$VACC1_H1N1_T) <- "TYPE OF FIRST H1N1 VACCINATION (DELIVERY MODE)"
label(NHFSPUF$VACC1_H1N1_Y) <- "YEAR OF FIRST H1N1 VACCINATION"

label(NHFSPUF$VACC1_SEAS_M) <- "MONTH OF FIRST SEASONAL VACCINATION"
label(NHFSPUF$VACC1_SEAS_T) <- "TYPE OF FIRST SEASONAL VACCINATION (DELIVERY MODE)"
label(NHFSPUF$VACC1_SEAS_Y) <- "YEAR OF FIRST SEASONAL VACCINATION"
label(NHFSPUF$VACC2_H1N1_M) <- "MONTH OF SECOND H1N1 VACCINATION"
label(NHFSPUF$VACC2_H1N1_T) <- "TYPE OF SECOND H1N1 VACCINATION (DELIVERY MODE)"

label(NHFSPUF$VACC2_H1N1_Y) <- "YEAR OF SECOND H1N1 VACCINATION"
label(NHFSPUF$VACC2_SEAS_M) <- "MONTH OF SECOND SEASONAL VACCINATION"
label(NHFSPUF$VACC2_SEAS_T) <- "TYPE OF SECOND SEASONAL VACCINATION (DELIVERY MODE)"
label(NHFSPUF$VACC2_SEAS_Y) <- "YEAR OF SECOND SEASONAL VACCINATION"
label(NHFSPUF$B_H1N1_ANTIV) <- "BEHAVIORAL INDICATOR: TAKING ANTIVIRAL MEDICATIONS"

label(NHFSPUF$B_H1N1_AVOID) <- "BEHAVIORAL INDICATOR: AVOID CLOSE CONTACT WITH OTHERS WITH FLULIKE SYMPTOMS"
label(NHFSPUF$B_H1N1_FMASK) <- "BEHAVIORAL INDICATOR: BOUGHT A FACE MASK"
label(NHFSPUF$B_H1N1_HANDS) <- "BEHAVIORAL INDICATOR: WASHING HANDS"
label(NHFSPUF$B_H1N1_LARGE) <- "BEHAVIORAL INDICATOR: REDUCED TIME AT LARGE GATHERINGS"
label(NHFSPUF$B_H1N1_RCONT) <- "BEHAVIORAL INDICATOR: REDUCED CONTACT OUTSIDE THE HOME"

label(NHFSPUF$B_H1N1_TOUCH) <- "BEHAVIORAL INDICATOR: AVOID TOUCHING EYES, NOSE, OR MOUTH"
label(NHFSPUF$CONCERN_DKNW_F) <- "H1N1 CONCERN LEVEL UNKNOWN"
label(NHFSPUF$CONCERN_NONE_F) <- "NOT AT ALL CONCERNED ABOUT H1N1 FLU"
label(NHFSPUF$CONCERN_NOTV_F) <- "NOT VERY CONCERNED ABOUT H1N1 FLU"
label(NHFSPUF$CONCERN_REFD_F) <- "H1N1 CONCERN LEVEL REFUSED"

label(NHFSPUF$CONCERN_SOME_F) <- "SOMEWHAT CONCERNED ABOUT H1N1 FLU"
label(NHFSPUF$CONCERN_VERY_F) <- "VERY CONCERNED ABOUT H1N1 FLU"
label(NHFSPUF$HQ23) <- "OPINION: EFFECTIVENESS OF H1N1 VACCINE"
label(NHFSPUF$HQ24) <- "OPINION: RISK OF GETTING SICK WITH H1N1 FLU WITHOUT VACCINE"
label(NHFSPUF$HQ24_B) <- "OPINION: WORRY ABOUT GETTING SICK FROM THE H1N1 VACCINE"

label(NHFSPUF$INT_H1N1_DKNW_F) <- "INTENT TO GET H1N1 VACCINE (FOR SELF OR CHILD) UNKNOWN"
label(NHFSPUF$INT_H1N1_DNOT_F) <- "DEFINITELY NO INTENT TO GET H1N1 VACCINE (FOR SELF OR CHILD)"
label(NHFSPUF$INT_H1N1_DYES_F) <- "DEFINITE INTENT TO GET H1N1 VACCINE (FOR SELF OR CHILD)"
label(NHFSPUF$INT_H1N1_PNOT_F) <- "IMPROBABLE INTENT TO GET H1N1 VACCINE (FOR SELF OR CHILD)"
label(NHFSPUF$INT_H1N1_PYES_F) <- "PROBABLE INTENT TO GET H1N1 VACCINE (FOR SELF OR CHILD)"

label(NHFSPUF$INT_H1N1_REFD_F) <- "INTENT TO GET H1N1 VACCINE (FOR SELF OR CHILD) REFUSED"
label(NHFSPUF$INT_NEXT_DKNW_F) <- "INTENT TO GET SEAS VACCINE NEXT SEASON (2010) UNKNOWN"
label(NHFSPUF$INT_NEXT_DNOT_F) <- "DEFINITELY NO INTENT TO GET SEAS VACCINE NEXT SEASON (2010)"
label(NHFSPUF$INT_NEXT_DYES_F) <- "DEFINITE INTENT TO GET SEAS VACCINE NEXT SEASON (2010)"
label(NHFSPUF$INT_NEXT_PNOT_F) <- "IMPROBABLE INTENT TO GET SEAS VACCINE NEXT SEASON (2010)"

label(NHFSPUF$INT_NEXT_PYES_F) <- "PROBABLE INTENT TO GET SEAS VACCINE NEXT SEASON (2010)"
label(NHFSPUF$INT_NEXT_REFD_F) <- "INTENT TO GET SEAS VACCINE NEXT SEASON (2010) REFUSED"
label(NHFSPUF$INT_SEAS_DKNW_F) <- "INTENT TO GET SEAS VACCINE (FOR SELF OR CHILD) UNKNOWN"
label(NHFSPUF$INT_SEAS_DNOT_F) <- "DEFINITELY NO INTENT TO GET SEAS VACCINE (FOR SELF OR CHILD)"
label(NHFSPUF$INT_SEAS_DYES_F) <- "DEFINITE INTENT TO GET SEAS VACCINE (FOR SELF OR CHILD)"

label(NHFSPUF$INT_SEAS_PNOT_F) <- "IMPROBABLE INTENT TO GET SEAS VACCINE (FOR SELF OR CHILD)"
label(NHFSPUF$INT_SEAS_PYES_F) <- "PROBABLE INTENT TO GET SEAS VACCINE (FOR SELF OR CHILD)"
label(NHFSPUF$INT_SEAS_REFD_F) <- "INTENT TO GET SEAS VACCINE (FOR SELF OR CHILD) REFUSED"
label(NHFSPUF$KNOW_H1N1_ALOT_F) <- "A LOT OF KNOWLEDGE ABOUT H1N1 FLU"
label(NHFSPUF$KNOW_H1N1_DKNW_F) <- "KNOWLEDGE LEVEL ABOUT H1N1 FLU UNKNOWN"

label(NHFSPUF$KNOW_H1N1_LITL_F) <- "A LITTLE KNOWLEDGE ABOUT H1N1 FLU"
label(NHFSPUF$KNOW_H1N1_NONE_F) <- "NO KNOWLEDGE ABOUT H1N1 FLU"
label(NHFSPUF$KNOW_H1N1_REFD_F) <- "KNOWLEDGE LEVEL ABOUT H1N1 FLU REFUSED"
label(NHFSPUF$PLACE_H1N1_CLIN_F) <- "MOST RECENT H1N1 VACCINE RECEIVED AT A CLINIC OR HEALTH CENTER"
label(NHFSPUF$PLACE_H1N1_DEPT_F) <- "MOST RECENT H1N1 VACCINE RECEIVED AT THE HEALTH DEPARTMENT"

label(NHFSPUF$PLACE_H1N1_DKNW_F) <- "PLACE OF MOST RECENT H1N1 VACCINE RECEIVED UNKNOWN"
label(NHFSPUF$PLACE_H1N1_DOCT_F) <- "MOST RECENT H1N1 VACCINE RECEIVED AT A DOCTORS OFFICE"
label(NHFSPUF$PLACE_H1N1_HOSP_F) <- "MOST RECENT H1N1 VACCINE RECEIVED AT A HOSPITAL"
label(NHFSPUF$PLACE_H1N1_MTRY_F) <- "MOST RECENT H1N1 VACCINE RECEIVED AT A MILITARY FACILITY"
label(NHFSPUF$PLACE_H1N1_OTHM_F) <- "MOST RECENT H1N1 VACCINE RECEIVED AT AN OTHER MEDICAL PLACE"

label(NHFSPUF$PLACE_H1N1_OTHN_F) <- "MOST RECENT H1N1 VACCINE RECEIVED AT AN OTHER NON-MEDICAL PLACE"
label(NHFSPUF$PLACE_H1N1_PHRM_F) <- "MOST RECENT H1N1 VACCINE RECEIVED AT A PHARMACY"
label(NHFSPUF$PLACE_H1N1_REFD_F) <- "PLACE OF MOST RECENT H1N1 VACCINE RECEIVED REFUSED"
label(NHFSPUF$PLACE_H1N1_SCHL_F) <- "MOST RECENT H1N1 VACCINE RECEIVED AT A SCHOOL"
label(NHFSPUF$PLACE_H1N1_SCTR_F) <- "MOST RECENT H1N1 VACCINE RECEIVED AT A SENIOR CENTER"

label(NHFSPUF$PLACE_H1N1_SMKT_F) <- "MOST RECENT H1N1 VACCINE RECEIVED AT A SUPERMARKET"
label(NHFSPUF$PLACE_H1N1_WORK_F) <- "MOST RECENT H1N1 VACCINE RECEIVED AT THE WORKPLACE"
label(NHFSPUF$PLACE_SEAS_CLIN_F) <- "MOST RECENT SEAS VACCINE RECEIVED AT A CLINIC OR HEALTH CENTER"
label(NHFSPUF$PLACE_SEAS_DEPT_F) <- "MOST RECENT SEAS VACCINE RECEIVED AT THE HEALTH DEPARTMENT"
label(NHFSPUF$PLACE_SEAS_DKNW_F) <- "PLACE OF MOST RECENT SEAS VACCINE RECEIVED UNKNOWN"

label(NHFSPUF$PLACE_SEAS_DOCT_F) <- "MOST RECENT SEAS VACCINE RECEIVED AT A DOCTORS OFFICE"
label(NHFSPUF$PLACE_SEAS_HOSP_F) <- "MOST RECENT SEAS VACCINE RECEIVED AT A HOSPITAL"
label(NHFSPUF$PLACE_SEAS_MTRY_F) <- "MOST RECENT SEASONAL VACCINE RECEIVED AT A MILITARY FACILITY"
label(NHFSPUF$PLACE_SEAS_OTHM_F) <- "MOST RECENT SEAS VACCINE RECEIVED AT AN OTHER MEDICAL PLACE"
label(NHFSPUF$PLACE_SEAS_OTHN_F) <- "MOST RECENT SEAS VACCINE RECEIVED AT AN OTHER NON-MEDICAL PLACE"

label(NHFSPUF$PLACE_SEAS_PHRM_F) <- "MOST RECENT SEAS VACCINE RECEIVED AT A PHARMACY"
label(NHFSPUF$PLACE_SEAS_REFD_F) <- "PLACE OF MOST RECENT SEAS VACCINE RECEIVED REFUSED"
label(NHFSPUF$PLACE_SEAS_SCHL_F) <- "MOST RECENT SEAS VACCINE RECEIVED AT A SCHOOL"
label(NHFSPUF$PLACE_SEAS_SCTR_F) <- "MOST RECENT SEASONAL VACCINE RECEIVED AT A SENIOR CENTER"
label(NHFSPUF$PLACE_SEAS_SMKT_F) <- "MOST RECENT SEASONAL VACCINE RECEIVED AT A SUPERMARKET"

label(NHFSPUF$PLACE_SEAS_WORK_F) <- "MOST RECENT SEAS VACCINE RECEIVED AT THE WORKPLACE"
label(NHFSPUF$Q23) <- "OPINION: EFFECTIVENESS OF SEASONAL VACCINE"
label(NHFSPUF$Q24) <- "OPINION: RISK OF GETTING SICK WITH SEASONAL FLU WITHOUT VACCINE"
label(NHFSPUF$Q24_B) <- "OPINION: WORRY ABOUT GETTING SICK FROM THE SEASONAL VACCINE"
label(NHFSPUF$REAS_NOH1N1_AHAD_F) <- "H1N1 VACCINE NOT RECEIVED BECAUSE ALREADY HAD H1N1"

label(NHFSPUF$REAS_NOH1N1_ALLG_F) <- "H1N1 VACCINE NOT RECEIVED BECAUSE OF ALLERGIES"
label(NHFSPUF$REAS_NOH1N1_CANT_F) <- "H1N1 VACCINE NOT RECEIVED BECAUSE TRIED BUT COULDN'T GET THE VACCINE"
label(NHFSPUF$REAS_NOH1N1_COST_F) <- "H1N1 VACCINE NOT RECEIVED BECAUSE IT COSTS TOO MUCH"
label(NHFSPUF$REAS_NOH1N1_DKNW_F) <- "REASON H1N1 VACCINE NOT RECEIVED UNKNOWN"
label(NHFSPUF$REAS_NOH1N1_DWRK_F) <- "H1N1 VACCINE NOT RECEIVED BECAUSE VACCINE DOESN’T WORK"

label(NHFSPUF$REAS_NOH1N1_GOTO_F) <- "H1N1 VACCINE NOT RECEIVED BECAUSE UNSURE WHERE TO GO / WHO TO CALL"
label(NHFSPUF$REAS_NOH1N1_NDOC_F) <- "H1N1 VACCINE NOT RECEIVED BECAUSE DOCTOR HASN'T RECOMMENDED IT"
label(NHFSPUF$REAS_NOH1N1_NEVR_F) <- "H1N1 VACCINE NOT RECEIVED BECAUSE NEVER GETS FLU VACCINES / DOESN'T BELIEVE IN THEM"
label(NHFSPUF$REAS_NOH1N1_NNDD_F) <- "H1N1 VACCINE NOT RECEIVED BECAUSE IT IS NOT NEEDED"
label(NHFSPUF$REAS_NOH1N1_NOTA_F) <- "H1N1 VACCINE NOT RECEIVED BECAUSE VACCINE IS NOT AVAILABLE"

label(NHFSPUF$REAS_NOH1N1_OTHR_F) <- "H1N1 VACCINE NOT RECEIVED BECAUSE OF ANOTHER REASON"
label(NHFSPUF$REAS_NOH1N1_REFD_F) <- "REASON H1N1 VACCINE NOT RECEIVED REFUSED"
label(NHFSPUF$REAS_NOH1N1_SAVE_F) <- "H1N1 VACCINE NOT RECEIVED BECAUSE WOULD RATHER SAVE DOSE FOR SOMEONE WHO NEEDS IT MORE"
label(NHFSPUF$REAS_NOH1N1_SEFF_F) <- "H1N1 VACCINE NOT RECEIVED BECAUSE OF SIDE EFFECTS WORRIES"
label(NHFSPUF$REAS_NOH1N1_TIME_F) <- "H1N1 VACCINE NOT RECEIVED BECAUSE HASN'T GOTTEN TO IT YET / HASN'T HAD TIME"

label(NHFSPUF$REAS_NOSEAS_AHAD_F) <- "SEASONAL VACCINE NOT RECEIVED BECAUSE HAS ALREADY GOTTEN THE FLU"
label(NHFSPUF$REAS_NOSEAS_ALLG_F) <- "SEAS VACCINE NOT RECEIVED BECAUSE OF ALLERGIES"
label(NHFSPUF$REAS_NOSEAS_CANT_F) <- "SEASONAL VACCINE NOT RECEIVED BECAUSE TRIED BUT COULDN'T GET THE VACCINE"
label(NHFSPUF$REAS_NOSEAS_COST_F) <- "SEAS VACCINE NOT RECEIVED BECAUSE IT COSTS TOO MUCH"
label(NHFSPUF$REAS_NOSEAS_DKNW_F) <- "REASON SEAS VACCINE NOT RECEIVED UNKNOWN"

label(NHFSPUF$REAS_NOSEAS_DWRK_F) <- "SEAS VACCINE NOT RECEIVED BECAUSE VACCINE DOESN’T WORK"
label(NHFSPUF$REAS_NOSEAS_GOTO_F) <- "SEASONAL VACCINE NOT RECEIVED BECAUSE UNSURE WHERE TO GO / WHO TO CALL"
label(NHFSPUF$REAS_NOSEAS_NDOC_F) <- "SEASONAL VACCINE NOT RECEIVED BECAUSE DOCTOR HASN'T RECOMMENDED IT"
label(NHFSPUF$REAS_NOSEAS_NEVR_F) <- "SEASONAL VACCINE NOT RECEIVED BECAUSE NEVER GETS FLU VACCINES / DOESN'T BELIEVE IN THEM"
label(NHFSPUF$REAS_NOSEAS_NNDD_F) <- "SEAS VACCINE NOT RECEIVED BECAUSE IT IS NOT NEEDED"

label(NHFSPUF$REAS_NOSEAS_NOTA_F) <- "SEAS VACCINE NOT RECEIVED BECAUSE VACCINE IS NOT AVAILABLE"
label(NHFSPUF$REAS_NOSEAS_OTHR_F) <- "SEAS VACCINE NOT RECEIVED BECAUSE OF ANOTHER REASON"
label(NHFSPUF$REAS_NOSEAS_REFD_F) <- "REASON SEAS VACCINE NOT RECEIVED REFUSED"
label(NHFSPUF$REAS_NOSEAS_SAVE_F) <- "SEASONAL VACCINE NOT RECEIVED BECAUSE WOULD RATHER SAVE DOSE FOR SOMEONE WHO NEEDS IT MORE"
label(NHFSPUF$REAS_NOSEAS_SEFF_F) <- "SEAS VACCINE NOT RECEIVED BECAUSE OF SIDE EFFECTS WORRIES"

label(NHFSPUF$REAS_NOSEAS_TIME_F) <- "SEASONAL VACCINE NOT RECEIVED BECAUSE HASN'T GOTTEN TO IT YET / HASN'T HAD TIME"
label(NHFSPUF$DOCREC_BOTH_F) <- "DOCTORS RECOMMENDATION FOR BOTH FLU VACCINES"
label(NHFSPUF$DOCREC_DKNW_F) <- "DOCTORS RECOMMENDATION UNKNOWN"
label(NHFSPUF$DOCREC_H1N1_F) <- "DOCTORS RECOMMENDATION FOR H1N1 VACCINE"
label(NHFSPUF$DOCREC_NTHR_F) <- "DOCTORS RECOMMENDATION FOR NEITHER H1N1 NOR SEASONAL VACCINE"

label(NHFSPUF$DOCREC_REFD_F) <- "DOCTORS RECOMMENDATION REFUSED"
label(NHFSPUF$DOCREC_SEAS_F) <- "DOCTORS RECOMMENDATION FOR SEASONAL VACCINE"
label(NHFSPUF$ILI_DIAG_H1N1_F) <- "DIAGNOSED WITH H1N1 WHEN TREATED FOR FEVER WITH COUGH OR SORE THROAT"
label(NHFSPUF$ILI_DIAG_SEAS_F) <- "DIAGNOSED WITH SEAS WHEN TREATED FOR FEVER WITH COUGH OR SORE THROAT"
label(NHFSPUF$ILI_F) <- "SICK WITH FEVER AND COUGH OR SORE THROAT IN PAST MONTH FLAG"

label(NHFSPUF$ILI_OTHER_F) <- "OTHER PEOPLE IN HOUSE WITH FEVER AND COUGH OR SORE THROAT FLAG"
label(NHFSPUF$ILI_TIME_OFF) <- "NUMBER OF DAYS OF SCHOOL OR WORK MISSED BECAUSE OF INFLUENZA-LIKE ILLNESS"
label(NHFSPUF$ILI_TREAT_F) <- "SICK WITH FEVER AND COUGH OR SORE THROAT IN PAST MONTH AND TREATED FLAG"
label(NHFSPUF$PSL_1) <- "ADULT WORKER IS ELIGIBLE FOR PAID SICK TIME OFF"
label(NHFSPUF$PSL_2) <- "ADULT WORKER CAN USE PAID SICK TIME OFF FOR SICK FAMILY MEMBER"

label(NHFSPUF$Q9) <- "HAS BEEN TO A DOCTOR/HOSPITAL/CLINIC SINCE AUGUST 2009"
label(NHFSPUF$Q9_NUM) <- "NUMBER OF TIMES SEEN DOCTOR SINCE AUGUST 2009"
label(NHFSPUF$CHRONIC_MED_F) <- "CHRONIC MEDICAL CONDITION FLAG"
label(NHFSPUF$CLOSE_UNDER6MO_F) <- "CLOSE CONTACT WITH CHILD UNDER 6 MONTHS FLAG"
label(NHFSPUF$HEALTH_WORKER_F) <- "WORKS IN HEALTH CARE FIELD FLAG"

label(NHFSPUF$PATIENT_CONTACT_F) <- "DIRECT PATIENT CONTACT FLAG"
label(NHFSPUF$AGEGRP) <- "AGE GROUP"
label(NHFSPUF$C_INSURE2) <- "HEALTH INSURANCE COVERAGE IS MEDICAID OR SCHIP PROGRAM"
label(NHFSPUF$EDUCATION_COMP) <- "ADULT SELF-REPORTED EDUCATION LEVEL"
label(NHFSPUF$HH_CHILD_R) <- "NUMBER OF CHILDREN IN THE HOUSEHOLD: RECODE"

label(NHFSPUF$HISP_I) <- "HISPANIC OR LATINO?: IMPUTED"
label(NHFSPUF$INC_CAT1) <- "HOUSEHOLD INCOME CATEGORY"
label(NHFSPUF$INC_POV) <- "POVERTY STATUS OF HOUSEHOLD"
label(NHFSPUF$INC_REF) <- "REFERENCE YEAR FOR HOUSEHOLD INCOME"
label(NHFSPUF$INSURE) <- "HAS HEALTH INSURANCE COVERAGE"

label(NHFSPUF$MARITAL) <- "MARITAL STATUS"
label(NHFSPUF$N_ADULT_R) <- "NUMBER ADULTS IN THE HOUSEHOLD: RECODE"
label(NHFSPUF$N_PEOPLE_R) <- "NUMBER ADULTS IN THE HOUSEHOLD: RECODE"
label(NHFSPUF$Q95) <- "WORK STATUS"
label(NHFSPUF$Q95_INDSTR) <- "EMPLOYMENT INDUSTRY TYPE CODE"

label(NHFSPUF$Q95_OCCPN) <- "EMPLOYMENT OCCUPATION TYPE CODE"
label(NHFSPUF$RACE_I_R) <- "RACE WITH MULTIRACE CATEGORY: IMPUTED"
label(NHFSPUF$RACEETH4_I) <- "FOUR-LEVEL RACE/ETHNICITY: IMPUTED"
label(NHFSPUF$RENT_OWN_R) <- "IS HOME RENTED OR OWNED"
label(NHFSPUF$SEX_I) <- "GENDER OF PERSON: IMPUTED"

label(NHFSPUF$CEN_REG) <- "TRUE CENSUS REGION OF RESIDENCE (1=NORTHEAST 2=MIDWEST 3=SOUTH 4=WEST)"
label(NHFSPUF$FLUWT) <- "FINAL CUMULATIVE WEIGHT"
label(NHFSPUF$HHS_REGION) <- "HHS SURVEILLANCE REGION NUMBER"
label(NHFSPUF$MSA_DEF) <- "DATE OF CENSUS MSA DEFINITIONS USED TO CREATE MSA3_I"
label(NHFSPUF$MSA3_I) <- "3-CATEGORY MSA STATUS: IMPUTED"

label(NHFSPUF$STATE) <- "STATE OF RESIDENCE"

############################################################################
# Step 5:   CREATE A PERMANENT R DATASET                                   #
############################################################################

save(NHFSPUF, file=paste(PUF, "/NHFSPUF.RData", sep=""))

############################################################################
# Step 6:   ASSIGN FORMATS                                                 #
#	  FORMATS ARE APPLICABLE ONLY TO CATEGORICAL VARIABLES	IN R           #
############################################################################

NHFSPUF$INT_MONTH <- factor(NHFSPUF$INT_MONTH, levels=NOFMTClevels, labels=NOFMTClabels)
NHFSPUF$VACC_H1N1_F <- factor(NHFSPUF$VACC_H1N1_F, levels=FLAGlevels, labels=FLAGlabels)
NHFSPUF$VACC_PNEU_F <- factor(NHFSPUF$VACC_PNEU_F, levels=FLAGlevels, labels=FLAGlabels)
NHFSPUF$VACC_SEAS_F <- factor(NHFSPUF$VACC_SEAS_F, levels=FLAGlevels, labels=FLAGlabels)
NHFSPUF$B_H1N1_ANTIV <- factor(NHFSPUF$B_H1N1_ANTIV, levels=FLAGlevels, labels=FLAGlabels)

NHFSPUF$B_H1N1_AVOID <- factor(NHFSPUF$B_H1N1_AVOID, levels=FLAGlevels, labels=FLAGlabels)
NHFSPUF$B_H1N1_FMASK <- factor(NHFSPUF$B_H1N1_FMASK, levels=FLAGlevels, labels=FLAGlabels)
NHFSPUF$B_H1N1_HANDS <- factor(NHFSPUF$B_H1N1_HANDS, levels=FLAGlevels, labels=FLAGlabels)
NHFSPUF$B_H1N1_LARGE <- factor(NHFSPUF$B_H1N1_LARGE, levels=FLAGlevels, labels=FLAGlabels)
NHFSPUF$B_H1N1_RCONT <- factor(NHFSPUF$B_H1N1_RCONT, levels=FLAGlevels, labels=FLAGlabels)

NHFSPUF$B_H1N1_TOUCH <- factor(NHFSPUF$B_H1N1_TOUCH, levels=FLAGlevels, labels=FLAGlabels)
NHFSPUF$CONCERN_DKNW_F <- factor(NHFSPUF$CONCERN_DKNW_F, levels=FLAGlevels, labels=FLAGlabels)
NHFSPUF$CONCERN_NONE_F <- factor(NHFSPUF$CONCERN_NONE_F, levels=FLAGlevels, labels=FLAGlabels)
NHFSPUF$CONCERN_NOTV_F <- factor(NHFSPUF$CONCERN_NOTV_F, levels=FLAGlevels, labels=FLAGlabels)
NHFSPUF$CONCERN_REFD_F <- factor(NHFSPUF$CONCERN_REFD_F, levels=FLAGlevels, labels=FLAGlabels)

NHFSPUF$CONCERN_SOME_F <- factor(NHFSPUF$CONCERN_SOME_F, levels=FLAGlevels, labels=FLAGlabels)
NHFSPUF$CONCERN_VERY_F <- factor(NHFSPUF$CONCERN_VERY_F, levels=FLAGlevels, labels=FLAGlabels)
NHFSPUF$INT_H1N1_DKNW_F <- factor(NHFSPUF$INT_H1N1_DKNW_F, levels=FLAGlevels, labels=FLAGlabels)
NHFSPUF$INT_H1N1_DNOT_F <- factor(NHFSPUF$INT_H1N1_DNOT_F, levels=FLAGlevels, labels=FLAGlabels)
NHFSPUF$INT_H1N1_DYES_F <- factor(NHFSPUF$INT_H1N1_DYES_F, levels=FLAGlevels, labels=FLAGlabels)

NHFSPUF$INT_H1N1_PNOT_F <- factor(NHFSPUF$INT_H1N1_PNOT_F, levels=FLAGlevels, labels=FLAGlabels)
NHFSPUF$INT_H1N1_PYES_F <- factor(NHFSPUF$INT_H1N1_PYES_F, levels=FLAGlevels, labels=FLAGlabels)
NHFSPUF$INT_H1N1_REFD_F <- factor(NHFSPUF$INT_H1N1_REFD_F, levels=FLAGlevels, labels=FLAGlabels)
NHFSPUF$INT_NEXT_DKNW_F <- factor(NHFSPUF$INT_NEXT_DKNW_F, levels=FLAGlevels, labels=FLAGlabels)
NHFSPUF$INT_NEXT_DNOT_F <- factor(NHFSPUF$INT_NEXT_DNOT_F, levels=FLAGlevels, labels=FLAGlabels)

NHFSPUF$INT_NEXT_DYES_F <- factor(NHFSPUF$INT_NEXT_DYES_F, levels=FLAGlevels, labels=FLAGlabels)
NHFSPUF$INT_NEXT_PNOT_F <- factor(NHFSPUF$INT_NEXT_PNOT_F, levels=FLAGlevels, labels=FLAGlabels)
NHFSPUF$INT_NEXT_PYES_F <- factor(NHFSPUF$INT_NEXT_PYES_F, levels=FLAGlevels, labels=FLAGlabels)
NHFSPUF$INT_NEXT_REFD_F <- factor(NHFSPUF$INT_NEXT_REFD_F, levels=FLAGlevels, labels=FLAGlabels)
NHFSPUF$INT_SEAS_DKNW_F <- factor(NHFSPUF$INT_SEAS_DKNW_F, levels=FLAGlevels, labels=FLAGlabels)

NHFSPUF$INT_SEAS_DNOT_F <- factor(NHFSPUF$INT_SEAS_DNOT_F, levels=FLAGlevels, labels=FLAGlabels)
NHFSPUF$INT_SEAS_DYES_F <- factor(NHFSPUF$INT_SEAS_DYES_F, levels=FLAGlevels, labels=FLAGlabels)
NHFSPUF$INT_SEAS_PNOT_F <- factor(NHFSPUF$INT_SEAS_PNOT_F, levels=FLAGlevels, labels=FLAGlabels)
NHFSPUF$INT_SEAS_PYES_F <- factor(NHFSPUF$INT_SEAS_PYES_F, levels=FLAGlevels, labels=FLAGlabels)
NHFSPUF$INT_SEAS_REFD_F <- factor(NHFSPUF$INT_SEAS_REFD_F, levels=FLAGlevels, labels=FLAGlabels)

NHFSPUF$KNOW_H1N1_ALOT_F <- factor(NHFSPUF$KNOW_H1N1_ALOT_F, levels=FLAGlevels, labels=FLAGlabels)
NHFSPUF$KNOW_H1N1_DKNW_F <- factor(NHFSPUF$KNOW_H1N1_DKNW_F, levels=FLAGlevels, labels=FLAGlabels)
NHFSPUF$KNOW_H1N1_LITL_F <- factor(NHFSPUF$KNOW_H1N1_LITL_F, levels=FLAGlevels, labels=FLAGlabels)
NHFSPUF$KNOW_H1N1_NONE_F <- factor(NHFSPUF$KNOW_H1N1_NONE_F, levels=FLAGlevels, labels=FLAGlabels)
NHFSPUF$KNOW_H1N1_REFD_F <- factor(NHFSPUF$KNOW_H1N1_REFD_F, levels=FLAGlevels, labels=FLAGlabels)

NHFSPUF$PLACE_H1N1_CLIN_F <- factor(NHFSPUF$PLACE_H1N1_CLIN_F, levels=FLAGlevels, labels=FLAGlabels)
NHFSPUF$PLACE_H1N1_DEPT_F <- factor(NHFSPUF$PLACE_H1N1_DEPT_F, levels=FLAGlevels, labels=FLAGlabels)
NHFSPUF$PLACE_H1N1_DKNW_F <- factor(NHFSPUF$PLACE_H1N1_DKNW_F, levels=FLAGlevels, labels=FLAGlabels)
NHFSPUF$PLACE_H1N1_DOCT_F <- factor(NHFSPUF$PLACE_H1N1_DOCT_F, levels=FLAGlevels, labels=FLAGlabels)
NHFSPUF$PLACE_H1N1_HOSP_F <- factor(NHFSPUF$PLACE_H1N1_HOSP_F, levels=FLAGlevels, labels=FLAGlabels)

NHFSPUF$PLACE_H1N1_MTRY_F <- factor(NHFSPUF$PLACE_H1N1_MTRY_F, levels=FLAGlevels, labels=FLAGlabels)
NHFSPUF$PLACE_H1N1_OTHM_F <- factor(NHFSPUF$PLACE_H1N1_OTHM_F, levels=FLAGlevels, labels=FLAGlabels)
NHFSPUF$PLACE_H1N1_OTHN_F <- factor(NHFSPUF$PLACE_H1N1_OTHN_F, levels=FLAGlevels, labels=FLAGlabels)
NHFSPUF$PLACE_H1N1_PHRM_F <- factor(NHFSPUF$PLACE_H1N1_PHRM_F, levels=FLAGlevels, labels=FLAGlabels)
NHFSPUF$PLACE_H1N1_REFD_F <- factor(NHFSPUF$PLACE_H1N1_REFD_F, levels=FLAGlevels, labels=FLAGlabels)

NHFSPUF$PLACE_H1N1_SCHL_F <- factor(NHFSPUF$PLACE_H1N1_SCHL_F, levels=FLAGlevels, labels=FLAGlabels)
NHFSPUF$PLACE_H1N1_SCTR_F <- factor(NHFSPUF$PLACE_H1N1_SCTR_F, levels=FLAGlevels, labels=FLAGlabels)
NHFSPUF$PLACE_H1N1_SMKT_F <- factor(NHFSPUF$PLACE_H1N1_SMKT_F, levels=FLAGlevels, labels=FLAGlabels)
NHFSPUF$PLACE_H1N1_WORK_F <- factor(NHFSPUF$PLACE_H1N1_WORK_F, levels=FLAGlevels, labels=FLAGlabels)
NHFSPUF$PLACE_SEAS_CLIN_F <- factor(NHFSPUF$PLACE_SEAS_CLIN_F, levels=FLAGlevels, labels=FLAGlabels)

NHFSPUF$PLACE_SEAS_DEPT_F <- factor(NHFSPUF$PLACE_SEAS_DEPT_F, levels=FLAGlevels, labels=FLAGlabels)
NHFSPUF$PLACE_SEAS_DKNW_F <- factor(NHFSPUF$PLACE_SEAS_DKNW_F, levels=FLAGlevels, labels=FLAGlabels)
NHFSPUF$PLACE_SEAS_DOCT_F <- factor(NHFSPUF$PLACE_SEAS_DOCT_F, levels=FLAGlevels, labels=FLAGlabels)
NHFSPUF$PLACE_SEAS_HOSP_F <- factor(NHFSPUF$PLACE_SEAS_HOSP_F, levels=FLAGlevels, labels=FLAGlabels)
NHFSPUF$PLACE_SEAS_MTRY_F <- factor(NHFSPUF$PLACE_SEAS_MTRY_F, levels=FLAGlevels, labels=FLAGlabels)

NHFSPUF$PLACE_SEAS_OTHM_F <- factor(NHFSPUF$PLACE_SEAS_OTHM_F, levels=FLAGlevels, labels=FLAGlabels)
NHFSPUF$PLACE_SEAS_OTHN_F <- factor(NHFSPUF$PLACE_SEAS_OTHN_F, levels=FLAGlevels, labels=FLAGlabels)
NHFSPUF$PLACE_SEAS_PHRM_F <- factor(NHFSPUF$PLACE_SEAS_PHRM_F, levels=FLAGlevels, labels=FLAGlabels)
NHFSPUF$PLACE_SEAS_REFD_F <- factor(NHFSPUF$PLACE_SEAS_REFD_F, levels=FLAGlevels, labels=FLAGlabels)
NHFSPUF$PLACE_SEAS_SCHL_F <- factor(NHFSPUF$PLACE_SEAS_SCHL_F, levels=FLAGlevels, labels=FLAGlabels)

NHFSPUF$PLACE_SEAS_SCTR_F <- factor(NHFSPUF$PLACE_SEAS_SCTR_F, levels=FLAGlevels, labels=FLAGlabels)
NHFSPUF$PLACE_SEAS_SMKT_F <- factor(NHFSPUF$PLACE_SEAS_SMKT_F, levels=FLAGlevels, labels=FLAGlabels)
NHFSPUF$PLACE_SEAS_WORK_F <- factor(NHFSPUF$PLACE_SEAS_WORK_F, levels=FLAGlevels, labels=FLAGlabels)
NHFSPUF$REAS_NOH1N1_AHAD_F <- factor(NHFSPUF$REAS_NOH1N1_AHAD_F, levels=FLAGlevels, labels=FLAGlabels)
NHFSPUF$REAS_NOH1N1_ALLG_F <- factor(NHFSPUF$REAS_NOH1N1_ALLG_F, levels=FLAGlevels, labels=FLAGlabels)

NHFSPUF$REAS_NOH1N1_CANT_F <- factor(NHFSPUF$REAS_NOH1N1_CANT_F, levels=FLAGlevels, labels=FLAGlabels)
NHFSPUF$REAS_NOH1N1_COST_F <- factor(NHFSPUF$REAS_NOH1N1_COST_F, levels=FLAGlevels, labels=FLAGlabels)
NHFSPUF$REAS_NOH1N1_DKNW_F <- factor(NHFSPUF$REAS_NOH1N1_DKNW_F, levels=FLAGlevels, labels=FLAGlabels)
NHFSPUF$REAS_NOH1N1_DWRK_F <- factor(NHFSPUF$REAS_NOH1N1_DWRK_F, levels=FLAGlevels, labels=FLAGlabels)
NHFSPUF$REAS_NOH1N1_GOTO_F <- factor(NHFSPUF$REAS_NOH1N1_GOTO_F, levels=FLAGlevels, labels=FLAGlabels)

NHFSPUF$REAS_NOH1N1_NDOC_F <- factor(NHFSPUF$REAS_NOH1N1_NDOC_F, levels=FLAGlevels, labels=FLAGlabels)
NHFSPUF$REAS_NOH1N1_NEVR_F <- factor(NHFSPUF$REAS_NOH1N1_NEVR_F, levels=FLAGlevels, labels=FLAGlabels)
NHFSPUF$REAS_NOH1N1_NNDD_F <- factor(NHFSPUF$REAS_NOH1N1_NNDD_F, levels=FLAGlevels, labels=FLAGlabels)
NHFSPUF$REAS_NOH1N1_NOTA_F <- factor(NHFSPUF$REAS_NOH1N1_NOTA_F, levels=FLAGlevels, labels=FLAGlabels)
NHFSPUF$REAS_NOH1N1_OTHR_F <- factor(NHFSPUF$REAS_NOH1N1_OTHR_F, levels=FLAGlevels, labels=FLAGlabels)

NHFSPUF$REAS_NOH1N1_REFD_F <- factor(NHFSPUF$REAS_NOH1N1_REFD_F, levels=FLAGlevels, labels=FLAGlabels)
NHFSPUF$REAS_NOH1N1_SAVE_F <- factor(NHFSPUF$REAS_NOH1N1_SAVE_F, levels=FLAGlevels, labels=FLAGlabels)
NHFSPUF$REAS_NOH1N1_SEFF_F <- factor(NHFSPUF$REAS_NOH1N1_SEFF_F, levels=FLAGlevels, labels=FLAGlabels)
NHFSPUF$REAS_NOH1N1_TIME_F <- factor(NHFSPUF$REAS_NOH1N1_TIME_F, levels=FLAGlevels, labels=FLAGlabels)
NHFSPUF$REAS_NOSEAS_AHAD_F <- factor(NHFSPUF$REAS_NOSEAS_AHAD_F, levels=FLAGlevels, labels=FLAGlabels)

NHFSPUF$REAS_NOSEAS_ALLG_F <- factor(NHFSPUF$REAS_NOSEAS_ALLG_F, levels=FLAGlevels, labels=FLAGlabels)
NHFSPUF$REAS_NOSEAS_CANT_F <- factor(NHFSPUF$REAS_NOSEAS_CANT_F, levels=FLAGlevels, labels=FLAGlabels)
NHFSPUF$REAS_NOSEAS_COST_F <- factor(NHFSPUF$REAS_NOSEAS_COST_F, levels=FLAGlevels, labels=FLAGlabels)
NHFSPUF$REAS_NOSEAS_DKNW_F <- factor(NHFSPUF$REAS_NOSEAS_DKNW_F, levels=FLAGlevels, labels=FLAGlabels)
NHFSPUF$REAS_NOSEAS_DWRK_F <- factor(NHFSPUF$REAS_NOSEAS_DWRK_F, levels=FLAGlevels, labels=FLAGlabels)

NHFSPUF$REAS_NOSEAS_GOTO_F <- factor(NHFSPUF$REAS_NOSEAS_GOTO_F, levels=FLAGlevels, labels=FLAGlabels)
NHFSPUF$REAS_NOSEAS_NDOC_F <- factor(NHFSPUF$REAS_NOSEAS_NDOC_F, levels=FLAGlevels, labels=FLAGlabels)
NHFSPUF$REAS_NOSEAS_NEVR_F <- factor(NHFSPUF$REAS_NOSEAS_NEVR_F, levels=FLAGlevels, labels=FLAGlabels)
NHFSPUF$REAS_NOSEAS_NNDD_F <- factor(NHFSPUF$REAS_NOSEAS_NNDD_F, levels=FLAGlevels, labels=FLAGlabels)
NHFSPUF$REAS_NOSEAS_NOTA_F <- factor(NHFSPUF$REAS_NOSEAS_NOTA_F, levels=FLAGlevels, labels=FLAGlabels)

NHFSPUF$REAS_NOSEAS_OTHR_F <- factor(NHFSPUF$REAS_NOSEAS_OTHR_F, levels=FLAGlevels, labels=FLAGlabels)
NHFSPUF$REAS_NOSEAS_REFD_F <- factor(NHFSPUF$REAS_NOSEAS_REFD_F, levels=FLAGlevels, labels=FLAGlabels)
NHFSPUF$REAS_NOSEAS_SAVE_F <- factor(NHFSPUF$REAS_NOSEAS_SAVE_F, levels=FLAGlevels, labels=FLAGlabels)
NHFSPUF$REAS_NOSEAS_SEFF_F <- factor(NHFSPUF$REAS_NOSEAS_SEFF_F, levels=FLAGlevels, labels=FLAGlabels)
NHFSPUF$REAS_NOSEAS_TIME_F <- factor(NHFSPUF$REAS_NOSEAS_TIME_F, levels=FLAGlevels, labels=FLAGlabels)

NHFSPUF$DOCREC_BOTH_F <- factor(NHFSPUF$DOCREC_BOTH_F, levels=FLAGlevels, labels=FLAGlabels)
NHFSPUF$DOCREC_DKNW_F <- factor(NHFSPUF$DOCREC_DKNW_F, levels=FLAGlevels, labels=FLAGlabels)
NHFSPUF$DOCREC_H1N1_F <- factor(NHFSPUF$DOCREC_H1N1_F, levels=FLAGlevels, labels=FLAGlabels)
NHFSPUF$DOCREC_NTHR_F <- factor(NHFSPUF$DOCREC_NTHR_F, levels=FLAGlevels, labels=FLAGlabels)
NHFSPUF$DOCREC_REFD_F <- factor(NHFSPUF$DOCREC_REFD_F, levels=FLAGlevels, labels=FLAGlabels)

NHFSPUF$DOCREC_SEAS_F <- factor(NHFSPUF$DOCREC_SEAS_F, levels=FLAGlevels, labels=FLAGlabels)
NHFSPUF$ILI_DIAG_H1N1_F <- factor(NHFSPUF$ILI_DIAG_H1N1_F, levels=FLAGlevels, labels=FLAGlabels)
NHFSPUF$ILI_DIAG_SEAS_F <- factor(NHFSPUF$ILI_DIAG_SEAS_F, levels=FLAGlevels, labels=FLAGlabels)
NHFSPUF$ILI_F <- factor(NHFSPUF$ILI_F, levels=FLAGlevels, labels=FLAGlabels)
NHFSPUF$ILI_OTHER_F <- factor(NHFSPUF$ILI_OTHER_F, levels=FLAGlevels, labels=FLAGlabels)

NHFSPUF$ILI_TREAT_F <- factor(NHFSPUF$ILI_TREAT_F, levels=FLAGlevels, labels=FLAGlabels)
NHFSPUF$CHRONIC_MED_F <- factor(NHFSPUF$CHRONIC_MED_F, levels=FLAGlevels, labels=FLAGlabels)
NHFSPUF$CLOSE_UNDER6MO_F <- factor(NHFSPUF$CLOSE_UNDER6MO_F, levels=FLAGlevels, labels=FLAGlabels)
NHFSPUF$HEALTH_WORKER_F <- factor(NHFSPUF$HEALTH_WORKER_F, levels=FLAGlevels, labels=FLAGlabels)
NHFSPUF$PATIENT_CONTACT_F <- factor(NHFSPUF$PATIENT_CONTACT_F, levels=FLAGlevels, labels=FLAGlabels)

NHFSPUF$EDUCATION_COMP <- factor(NHFSPUF$EDUCATION_COMP, levels=EDUCATIONlevels, labels=EDUCATIONlabels)
NHFSPUF$INC_POV <- factor(NHFSPUF$INC_POV, levels=POVSTATlevels, labels=POVSTATlabels)
NHFSPUF$SEX_I <- factor(NHFSPUF$SEX_I, levels=GENDERlevels, labels=GENDERlabels)
NHFSPUF$HHS_REGION <- factor(NHFSPUF$HHS_REGION, levels=HHSREGIONlevels, labels=HHSREGIONlabels)
NHFSPUF$MSA3_I <- factor(NHFSPUF$MSA3_I, levels=MSAlevels, labels=MSAlabels)

NHFSPUF$CEN_REG <- factor(NHFSPUF$CEN_REG, levels=CENREGlevels, labels=CENREGlabels)
NHFSPUF$HISP_I <- factor(NHFSPUF$HISP_I, levels=HSPlevels, labels=HSPlabels)
NHFSPUF$RACEETH4_I <- factor(NHFSPUF$RACEETH4_I, levels=RACETH4_levels, labels=RACETH4_labels)
NHFSPUF$PSL_1 <- factor(NHFSPUF$PSL_1, levels=SFLAGlevels, labels=SFLAGlabels)
NHFSPUF$PSL_2 <- factor(NHFSPUF$PSL_2, levels=SFLAGlevels, labels=SFLAGlabels)

NHFSPUF$Q9 <- factor(NHFSPUF$Q9, levels=SFLAGlevels, labels=SFLAGlabels)
NHFSPUF$C_INSURE2 <- factor(NHFSPUF$C_INSURE2, levels=SFLAGlevels, labels=SFLAGlabels)
NHFSPUF$INSURE <- factor(NHFSPUF$INSURE, levels=SFLAGlevels, labels=SFLAGlabels)
NHFSPUF$VACC1_H1N1_M <- factor(NHFSPUF$VACC1_H1N1_M, levels=SHOTMONTHlevels, labels=SHOTMONTHlabels)
NHFSPUF$VACC1_SEAS_M <- factor(NHFSPUF$VACC1_SEAS_M, levels=SHOTMONTHlevels, labels=SHOTMONTHlabels)

NHFSPUF$VACC2_H1N1_M <- factor(NHFSPUF$VACC2_H1N1_M, levels=SHOTMONTHlevels, labels=SHOTMONTHlabels)
NHFSPUF$VACC2_SEAS_M <- factor(NHFSPUF$VACC2_SEAS_M, levels=SHOTMONTHlevels, labels=SHOTMONTHlabels)
NHFSPUF$VACC1_H1N1_Y <- factor(NHFSPUF$VACC1_H1N1_Y, levels=SHOTYEARlevels, labels=SHOTYEARlabels)
NHFSPUF$VACC1_SEAS_Y <- factor(NHFSPUF$VACC1_SEAS_Y, levels=SHOTYEARlevels, labels=SHOTYEARlabels)
NHFSPUF$VACC2_H1N1_Y <- factor(NHFSPUF$VACC2_H1N1_Y, levels=SHOTYEARlevels, labels=SHOTYEARlabels)

NHFSPUF$VACC2_SEAS_Y <- factor(NHFSPUF$VACC2_SEAS_Y, levels=SHOTYEARlevels, labels=SHOTYEARlabels)
NHFSPUF$Q9_NUM <- factor(NHFSPUF$Q9_NUM, levels=SNOFMTlevels, labels=SNOFMTlabels)
NHFSPUF$HQ23 <- factor(NHFSPUF$HQ23, levels=OPIN1_levels, labels=OPIN1_labels)
NHFSPUF$Q23 <- factor(NHFSPUF$Q23, levels=OPIN1_levels, labels=OPIN1_labels)
NHFSPUF$HQ24 <- factor(NHFSPUF$HQ24, levels=OPIN2_levels, labels=OPIN2_labels)

NHFSPUF$Q24 <- factor(NHFSPUF$Q24, levels=OPIN2_levels, labels=OPIN2_labels)
NHFSPUF$HQ24_B <- factor(NHFSPUF$HQ24_B, levels=OPIN3_levels, labels=OPIN3_labels)
NHFSPUF$Q24_B <- factor(NHFSPUF$Q24_B, levels=OPIN3_levels, labels=OPIN3_labels)
NHFSPUF$LANGUAGE <- factor(NHFSPUF$LANGUAGE, levels=LNGlevels, labels=LNGlabels)
NHFSPUF$VACC1_H1N1_T <- factor(NHFSPUF$VACC1_H1N1_T, levels=TYPElevels, labels=TYPElabels)

NHFSPUF$VACC1_SEAS_T <- factor(NHFSPUF$VACC1_SEAS_T, levels=TYPElevels, labels=TYPElabels)
NHFSPUF$VACC2_H1N1_T <- factor(NHFSPUF$VACC2_H1N1_T, levels=TYPElevels, labels=TYPElabels)
NHFSPUF$VACC2_SEAS_T <- factor(NHFSPUF$VACC2_SEAS_T, levels=TYPElevels, labels=TYPElabels)
NHFSPUF$INC_CAT1 <- factor(NHFSPUF$INC_CAT1, levels=INCCAT1_levels, labels=INCCAT1_labels)
NHFSPUF$SAMP_DESIG <- factor(NHFSPUF$SAMP_DESIG, levels=SAMPDESIG2_levels, labels=SAMPDESIG2_labels)

NHFSPUF$SUBGROUP <- factor(NHFSPUF$SUBGROUP, levels=SUBGRP2_levels, labels=SUBGRP2_labels)
NHFSPUF$AGEGRP <- factor(NHFSPUF$AGEGRP, levels=AGEGRP3_levels, labels=AGEGRP3_labels)
NHFSPUF$MARITAL <- factor(NHFSPUF$MARITAL, levels=MARSTAT2_levels, labels=MARSTAT2_labels)
NHFSPUF$RACE_I_R <- factor(NHFSPUF$RACE_I_R, levels=RCE2_levels, labels=RCE2_labels)
NHFSPUF$RENT_OWN_R <- factor(NHFSPUF$RENT_OWN_R, levels=RENTOWN2_levels, labels=RENTOWN2_labels)

NHFSPUF$Q95 <- factor(NHFSPUF$Q95, levels=WORKTYPE2_levels, labels=WORKTYPE2_labels)
NHFSPUF$Q95_INDSTR <- factor(NHFSPUF$Q95_INDSTR, levels=INDSTRlevels, labels=INDSTRlabels)
NHFSPUF$Q95_OCCPN <- factor(NHFSPUF$Q95_OCCPN, levels=OCCPNlevels, labels=OCCPNlabels)
NHFSPUF$STATE <- factor(NHFSPUF$STATE, levels=STATENUMlevels, labels=STATENUMlabels)

##########################################################################
# STEP 7:   CONTENTS AND STATISTICAL ESTIMATES(FREQUENCY) EXAMPLE        #
##########################################################################

#---CONTENTS---#
NHFSPUF.CONTENTS <- contents(NHFSPUF)$contents

print(NHFSPUF.CONTENTS)

#IN CASE THAT THE R CONSOLE CANNOT DISPLAY WHOLE CONTENTS,
#YOU CAN SAVE CONTENTS INTO A FILE
#write.table(NHFSPUF.CONTENTS, file=paste(PUF,"/file-name",sep=""))

#---UNWEIGHTED FREQUENCY---#
unwt_freq <- function(UNWT.VAR){#FUNCTION TO PRINT UNWEIGHTED FREQUENCIES

unwt.tab <- wtd.table(UNWT.VAR, weights= NULL, type='table')
unwtd.freq <- data.frame(cbind(
unwt.tab, round(unwt.tab/sum(unwt.tab)*100,2),
cumsum(unwt.tab), cumsum(round(unwt.tab/sum(unwt.tab)*100,2))))
names(unwtd.freq) <- c("Frequency", "Percent", "Cumulative Frequency", "Cumulative Percent")
unwtd.title <- paste(' NHFSPUF', 'UNWEIGHTED FREQUENCIES', label(UNWT.VAR), sep="\n")
label(unwtd.freq) <- unwtd.title

print(unwtd.freq)
}

UNWT.VAR <- NHFSPUF$AGEGRP	#INPUT A VARIABLE OF INTEREST
unwt_freq(UNWT.VAR)

#---WEIGHTED FREQUENCY---#
WT <- NHFSPUF$FLUWT		#INPUT A WEIGHT VARIABLE
WT.VAR <- NHFSPUF$AGEGRP 	#INPUT A VARIABLE OF INTEREST

wt.tab <- wtd.table(WT.VAR, weights= WT, type='table')
wtd.freq <- data.frame(cbind(
wt.tab, round(wt.tab/sum(wt.tab)*100,2),
cumsum(wt.tab), cumsum(round(wt.tab/sum(wt.tab)*100,2))))
names(wtd.freq) <- c("Frequency", "Percent", "Cumulative Frequency", "Cumulative Percent")
wtd.title <- paste(' NHFSPUF PUBLIC USE FILE', 'WEIGHTED FREQUENCIES', label(WT.VAR), sep="\n")
label(wtd.freq) <- wtd.title

print(wtd.freq)
